### ISSUE TITLE
Audios uploaded with metadata will always display metadata when sent

### ISSUE THREAD

**Issue by AtilioA** [heylouiz/myinstantsbot#15]
If a user sends an audio file with metadata (track or artist, it seems) through the /upload conversation, retrieving this instant through the bot will always send an audio message with metadata.

Silly example - first instant was sent as a .mp3 file with no metadata:
![nometadata](https://user-images.githubusercontent.com/27153776/134975819-12c3d179-2b46-46ec-b3dc-659ea8a067e3.png)
![metadata](https://user-images.githubusercontent.com/27153776/134975821-3e30d747-93b7-48f2-a40c-396a5e8fdb0c.png)

This can be undesirable as some users might not want to reveal an instant's content before it is played, and also because audio files frequently got a long and random string as their track title, in which case it will always pollute the instant message. Whether or not to delete metadata could be left open as an option to the user during the /upload conversation, being enabled by default.

Deleting metadata prior to actual upload is probably easily achieved through a library as https://pypi.org/project/mutagen/.
Thoughts?

**Comment by heylouiz** [comment]
Hi @AtilioA 
I wasn't aware of this.
Great suggestion, I think we can just strip the metadata out of the file since the fun part is not be able to tell the sound without hearing it.
